server:
    port: 8080

spring:
    application:
        name: "Backend Botequim Box"
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/db_botequimbox_dev
        username: postgres
        password: secret


    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: h2
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false

app:
    security:
        jwt:
            secret-key: 5368566D5971337436773979244226452948404D635166546A576E5A72347537
            access-expiration: 86400000   # 24 Hours
            refresh-expiration: 604800000 # 07 Days
